<?php
/**
 * @category Mulberry
 * @package Mulberry_Warranty
 * @author Mulberry <support@getmulberry.com>
 * @copyright Copyright (c) 2021 Mulberry Technology Inc., Ltd (http://www.getmulberry.com)
 * @license http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>

<?php
/**
 * @var $this Mulberry_Warranty_Block_Catalog_Product_View_Warranty_Container
 */
?>
<?php $product = $this->getProduct(); ?>

<?php if ($product->isSaleable()): ?>
    <?php if ($this->hasOptions()): ?>
        <div class="product-options product-options-mulberry">
            <div class="mulberry-inline-container"></div>
            <input type="hidden" id="warranty_hash" name="warranty[hash]" value=""/>
            <input type="hidden" id="warranty_sku" name="warranty[sku]" value="<?php echo $this->escapeHtml($product->getSku()); ?>"/>
        </div>
    <?php else: ?>
        <div class="product-options-mulberry">
            <div class="mulberry-inline-container"></div>
            <input type="hidden" id="warranty_hash" name="warranty[hash]" value=""/>
            <input type="hidden" id="warranty_sku" name="warranty[sku]" value="<?php echo $this->escapeHtml($product->getSku()); ?>"/>
        </div>
    <?php endif; ?>

    <script type="text/javascript">
        window.mulberryProductData = {
            product: {
                id: "<?= $this->escapeHtml($product->getSku()); ?>",
                title: "<?= $this->escapeHtml(htmlspecialchars($product->getName(), ENT_QUOTES | ENT_SUBSTITUTE, null, false)); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                url: "<?= $this->escapeUrl($product->getProductUrl()) ?>",
                images: <?= $this->getGalleryImagesInfo(); ?>,
                meta: {
                    breadcrumbs: <?= $this->getBreadcrumbsInfo(); ?>,
                },
                description: "<?= $this->escapeHtml($this->getProductDescription()); ?>"
            },
            activeSelection: {
                id: "<?= $this->escapeHtml($product->getSku()); ?>",
                title: "<?= $this->escapeHtml(htmlspecialchars($product->getName(), ENT_QUOTES | ENT_SUBSTITUTE, null, false)); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                url: "<?= $this->escapeUrl($product->getProductUrl()) ?>",
                images: <?= $this->getGalleryImagesInfo(); ?>,
                meta: {
                    breadcrumbs: <?= $this->getBreadcrumbsInfo(); ?>,
                },
                description: "<?= $this->escapeHtml($this->getProductDescription()); ?>"
            },
            originalSku: "<?= $this->escapeHtml($product->getSku()); ?>",
            originalPrice: <?= (float)$product->getFinalPrice(); ?>
        };

        window.mulberryConfigData = {
            "containerClass": "mulberry-inline-container",
            "magentoDomain": "<?= $this->getPlatformDomain(); ?>",
            "mulberryUrl": "<?= $this->getApiUrl(); ?>",
            "partnerUrl": "<?= $this->getPartnerUrl(); ?>",
            "retailerId": "<?= $this->getRetailerId() ?>",
            "publicToken": "<?= $this->getPublicToken(); ?>"
        };
    </script>
<?php endif; ?>
