<?php
/**
 * @category Mulberry
 * @package Mulberry\Warranty
 * @author Mulberry <support@getmulberry.com>
 * @copyright Copyright (c) 2018 Mulberry Technology Inc., Ltd (http://www.getmulberry.com)
 * @license http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>

<?php
/**
 * @var $this Mulberry_Warranty_Block_Catalog_Product_View_Warranty_Container
 */
?>
<?php $product = $this->getProduct(); ?>

<?php if ($product->isSaleable()): ?>
    <?php if ($this->hasOptions()): ?>
        <div class="product-options product-options-mulberry">
            <div class="mulberry-inline-container"></div>
            <input type="hidden" id="warranty" name="warranty[<?php echo $this->escapeHtml($product->getSku()); ?>]" value=""/>
        </div>
    <?php else: ?>
        <div class="product-options-mulberry">
            <div class="mulberry-inline-container"></div>
            <input type="hidden" id="warranty" name="warranty[<?php echo $this->escapeHtml($product->getSku()); ?>]" value=""/>
        </div>
    <?php endif; ?>

    <?php
    $description = $this->escapeHtml($product->getDescription());
    $description = preg_replace('/\r|\n/', ' ', $description);
    ?>
    <script type="text/javascript">
        window.mulberryProductData = {
            product: {
                id: "<?= $this->escapeHtml($product->getSku()); ?>",
                title: "<?= $this->escapeHtml($this->quoteEscape($product->getName())); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                description: "<?= $description; ?>"
            },
            originalSku: "<?= $this->escapeHtml($product->getSku()); ?>",
            originalPrice: <?= (float)$product->getFinalPrice(); ?>,
            originalDescription: "<?= $description; ?>"
        };

        window.mulberryConfigData = {
            "containerClass": "mulberry-inline-container",
            "magentoDomain": "<?= $this->getPlatformDomain(); ?>",
            "mulberryUrl": "<?= $this->getApiUrl(); ?>",
            "partnerUrl": "<?= $this->getPartnerUrl(); ?>",
            "retailerId": "<?= Mage::helper('mulberry_warranty')->getRetailerId() ?>"
        };
    </script>
<?php endif; ?>
