<?php
/**
 * @category Mulberry
 * @package Mulberry_Warranty
 * @author Mulberry <support@getmulberry.com>
 * @copyright Copyright (c) 2021 Mulberry Technology Inc., Ltd (http://www.getmulberry.com)
 * @license http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>

<div class="generate-and-download-wrapper">
    <?php echo $this->getGenerateAndDownloadButtonHtml() ?>
    <span class="generate-and-download-indicator" id="generate_and_download_span">
        <img class="generate_processing" hidden="hidden" alt="Generating" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif') ?>"/>
        <img class="generate_collected" hidden="hidden" alt="Downloading" style="margin:-3px 5px" src="<?php echo $this->getSkinUrl('images/rule_component_apply.gif'); ?>"/>
        <span id="generate_and_download_message_span"></span>
    </span>
</div>

<div class="download-wrapper">
    <?php echo $this->getDownloadButtonHtml() ?>
    <span class="download-indicator" id="download_span">
        <img class="download_processing" hidden="hidden" alt="Generating" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif') ?>"/>
        <img class="download_collected" hidden="hidden" alt="Downloading" style="margin:-3px 5px" src="<?php echo $this->getSkinUrl('images/rule_component_apply.gif'); ?>"/>
        <span id="download_message_span"></span>
    </span>
</div>

<script type="text/javascript">
    function download(filename, text) {
        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
        element.setAttribute('download', filename);

        element.style.display = 'none';
        document.body.appendChild(element);

        element.click();

        document.body.removeChild(element);
    }

    var generateSpan = $('generate_and_download_span');
    var downloadSpan = $('download_span');

    $('generate_and_download_button').addEventListener('click', function () {
        var messageSpan = $('generate_and_download_message_span');
        var currentPage = 1;
        var lastPage = 1;
        var data = [];
        var continueProcessing = true;
        generateSpan.getElementsByClassName('generate_collected')[0].hide();
        generateSpan.getElementsByClassName('generate_processing')[0].hide();
        do {
            var params = { page: currentPage }
            currentPage++;
            generateSpan.getElementsByTagName('span')[0].textContent = 'Processing ' + currentPage + ' of' + lastPage;
            new Ajax.Request('<?php echo $this->getGenerateAndDownloadAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: false,
                onCreate: function () {
                    generateSpan.getElementsByTagName('span')[0].textContent = 'Processing ' + currentPage + ' of' + lastPage;
                },
                onSuccess: function (response) {
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        generateSpan.getElementsByClassName('generate_collected')[0].show();
                    }
                    messageSpan.textContent = resultText;

                    var json = response.responseJSON;
                    lastPage = json.lastPage;
                    json.content.each(function (value) {
                        data.push(value);
                    });
                },
                onFail: function () {
                    continueProcessing = false;
                }
            });
        } while ((currentPage <= lastPage) && continueProcessing);
        generateSpan.getElementsByClassName('generate_processing')[0].hide();

        if (data && continueProcessing) {
            download('data.json', JSON.stringify(data));
        } else {
            messageSpan.textContent = 'Something went wrong, please try again';
        }
    });

    $('download_button').addEventListener('click', function () {
        var params = {};
        var messageSpan = $('download_message_span');
        new Ajax.Request('<?php echo $this->getDownloadAjaxUrl() ?>', {
            parameters:     params,
            loaderArea:     false,
            asynchronous:   true,
            onCreate: function() {
                downloadSpan.getElementsByClassName('download_collected')[0].hide();
                downloadSpan.getElementsByClassName('download_processing')[0].show();
                $('download_message_span').textContext = '';
            },
            onSuccess: function(response) {
                downloadSpan.getElementsByClassName('download_processing')[0].hide();

                var resultText = '';
                if (response.status > 200) {
                    resultText = response.statusText;
                } else {
                    resultText = 'Success. Download will start in a moment';
                    downloadSpan.getElementsByClassName('download_collected')[0].show();
                }
                messageSpan.textContent = resultText;

                var json = response.responseText.evalJSON();

                if (typeof json.content != 'undefined' && json.content !== '') {
                    download('data.json', JSON.stringify(json.content));
                } else {
                    messageSpan.textContent = 'Could not find data file';
                }
            }
        });
    });
</script>
